FROM strapi/base

WORKDIR /strapi

COPY ./package.json ./
COPY ./yarn.lock ./

RUN npm config set registry https://registry.npm.taobao.org && \
    yarn install

COPY . .

ENV NODE_ENV production

RUN yarn build

EXPOSE 1337

CMD ["yarn", "start"]